version: "3.8"
services:
  client:
    build: ./client
    ports:
      - 5713:5713
    volumes:
      - ./client:/app

  server:
    build: ./server
    ports:
      - 5000:5000
    volumes:
      - ./server:/app
