version : "3.8"
services:
  ngnix:
    restart : always
    image: nginx:latest
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    depends_on:
      - client
      - api
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - "./server:/app"
      - "/app/node_modules"
  
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - "./client:/app"
      - "/app/node_modules"
    command: npm run start
    tty: true


